sudo: false
language: python
matrix:
  include:
    - python: 3.10
      env: TOXENV=py310
    - python: 3.11
      env: TOXENV=py310
    - python: 3.12
      env: TOXENV=py310
    - python: 3.13
      env: TOXENV=py310
    - python: 3.10
      env: TOXENV=docs
    - python: 3.10
      env: TOXENV=pep8
install:
      - pip install tox
script:
      - tox
