[metadata]
name = jsonpath-rw-ext
summary = Extensions for JSONPath RW
description_file =
    README.rst
author = Mehdi Abaakouk
author_email = sileht@sileht.net
home_page = https://github.com/sileht/python-jsonpath-rw-ext
python_requires = >= 3.10
classifier =
    Development Status :: 5 - Production/Stable
    Intended Audience :: Developers
    License :: OSI Approved :: Apache Software License
    Programming Language :: Python
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3 :: Only
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12
    Programming Language :: Python :: 3.13

[files]
packages =
    jsonpath_rw_ext
